# Streamlit 실행 환경을 선택합니다.
FROM python:3.12-slim

# 컨테이너 내부 작업 폴더를 지정합니다.
WORKDIR /app

# 라이브러리 목록을 복사합니다.
COPY requirements.txt .

# 필요한 라이브러리를 설치합니다.
RUN pip install --no-cache-dir -r requirements.txt

# Streamlit 프로젝트 파일을 복사합니다.
COPY . .

# Streamlit 포트를 공개합니다.
EXPOSE 8501

# Streamlit 서버를 실행합니다.
CMD ["streamlit", "run", "streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]